### ISSUE TITLE
French translation (po file + some suggestions)

### ISSUE THREAD

**Issue by kirmaha** [paveloom-t/gnome-shell-memento-mori#1]
Hello,

I just translated the extension using the [POT file](https://github.com/paveloom-t/gnome-shell-memento-mori/tree/main/resources/po). I'm familiar with PO files but not with GitHub, so I'm not sure how to upload it (upload seems to be disabled in "po" folder). You can download it (fr.po) from [this link](https://nextcloud.nedra.be/s/z7NFt8fL2q8jff4).

I had three suggestions about the .pot file: 

- I think that the content of the "format string" field should also be translated. IMO, it is the most important part to translate, so the user doesn't have his top panel showing a language he does'nt understand. Would it be possible ?
- It would be nice if the extension's description was also translated. By that, I mean this text : "Make every second of your life count. Literally! This extension adds a counter to the panel which counts down the time you have left based on your birthday and life expectancy".
- Two lines are unclear to me :
1. "Available modifiers" ( -> "Available variables" ?)
2. "Number of years you expect to live through" -> looks like we are talking about remaining years rather than "from birth to death".

Have a nice day,
K.

**Comment by paveloom** [comment]
Hello there, @kirmaha. Thanks for the contribution!

> I'm familiar with PO files but not with GitHub, so I'm not sure how to upload it (upload seems to be disabled in "po" folder).

This is generally done by [creating a fork of the repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo), [adding a new file there](https://docs.github.com/en/repositories/working-with-files/managing-files/creating-new-files), then [proposing a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). However, all of this is not necessary, since a new translation is a single file, so sending it to me via other means (like you did above) is absolutely fine.

> I had three suggestions about the .pot file:
> * I think that the content of the "format string" field should also be translated. IMO, it is the most important part to translate, so the user doesn't have his top panel showing a language he doesn't understand. Would it be possible ?

Agreed. I added support for this in the 5480d96 commit. Note that there are now two strings related to the localized version of the format string: one for the placeholder in the widget and the other one is for the default value (making it one variable turned out to be unsafe). Note that the latter string *should* be wrapped in extra quotes, just like its `msgid`.

> * It would be nice if the extension's description was also translated. By that, I mean this text : "Make every second of your life count. Literally! This extension adds a counter to the panel which counts down the time you have left based on your birthday and life expectancy".

Unfortunately, neither Gnome Shell nor extensions.gnome.org support this. See [this upstream issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2288).

> * Two lines are unclear to me:
> 1. "Available modifiers" ( -> "Available variables" ?)

Agreed. "Variables" sounds better. I've changed it in 5480d96.

> 2. "Number of years you expect to live through" -> looks like we are talking about remaining years rather than "from birth to death".

Yes, it's supposed to mean total number of years a person expects to live through (life expectancy). "From birth to death" doesn't sound nicer, though... What would you suggest to change it to?

You can elaborate on further changes or you can provide me with an updated version of the `.po` file.

**Comment by kirmaha** [comment]
Hello,

Thanks for your expensive answer, love it!
I will gladly look into _merge requests_ in order to update the next fr.po update. For today, here comes the update related to your yesterday's .pot changes : [access the new fr.po file here](https://nextcloud.nedra.be/s/ff8XBCEK4fQPdfd).

> Note that there are now two strings related to the localized version of the format string: one for the placeholder in the widget and the other one is for the default value
I translated the two strings (not sure if that was supposed to be done).

> Yes, it's supposed to mean total number of years a person expects to live through (life expectancy). "From birth to death" doesn't sound nicer, though... What would you suggest to change it to?

I would go for something that suppresses possible confusion between "life expectancy at birth" (used in Memento Mori) and "life expectancy at a given age" (wrong but plausible interpretation of the current definition).

Current definition is : "Number of years you expect to live through"
Here are some suggestions that refers to an "age" or a "life span" rather than to a "number of years":
1. Statistical age that a person is expected to live until
2. Average age that people will be when they die
3. Average life span of an individual
Two other ideas:
- Maybe a "Find your own" button with a link could help the vast majority of people that does not know their own life expectancy: main ongoing reference is WHO -> https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years)
- Maybe adding "(depending on country and sex)" at the end of definition would be helpful but... not sure (too much information ?)

**Comment by paveloom** [comment]
> I translated the two strings (not sure if that was supposed to be done).

Yep, thanks.
 
> I would go for something that suppresses possible confusion between "life expectancy at birth" (used in Memento Mori) and "life expectancy at a given age" (wrong but plausible interpretation of the current definition).
> 
> Current definition is : "Number of years you expect to live through" Here are some suggestions that refers to an "age" or a "life span" rather than to a "number of years":
> 1. Statistical age that a person is expected to live until
> 2. Average age that people will be when they die
> 3. Average life span of an individual

These all sound formal. The reason why this setting is changeable by a user is that its purpose is to hold a *subjective* value of the life expectancy. That's why there is `you expect` in the current definition. For example, I expect to live at least 80 years, not only due to knowledge of statistical data in my region and globally, but also due to my lifestyle. So, this value is a subjective approximation of one's life expectancy at birth.

Actually, this last sentence could be it. How about the following description: "Life expectancy at birth in years"? Short and to the point. The subjective part comes from the fact that the field is changeable.

> Two other ideas:
> * Maybe a "Find your own" button with a link could help the vast majority of people that does not know their own life expectancy: main ongoing reference is WHO -> [who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years)](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years))

Same reasoning as above: it's too formal. Good resource, though. I think that if a user found this extension and installed it, they've already somewhat comprehended the fact of the shortness of live, so they probably have an idea of how much they can expect to have of it in total. If not, there are lots of sources (besides the aforementioned) to go to investigate.

> * Maybe adding "(depending on country and sex)" at the end of definition would be helpful but... not sure (too much information ?)

Yep, that's too much information. There is no hard limit, but for aesthetic reasons I expect the description to fit in one line (in all translations) in the widget with the default width of the window.

**Comment by kirmaha** [comment]
> How about the following description: "Life expectancy at birth in years"? Short and to the point. The subjective part comes from the fact that the field is changeable.

I agree with you. This combines standard formulation/definition with openness to subjectivity.

In that perspective, I understand also agree the two last suggestions are not suitable (healthcare professional here, so... occupational hazard, surely ! :D )

**Comment by paveloom** [comment]
Aight, I changed the wording in the fa84b36edfbfff1247d48f9e3362961f1a1f06a4 commit. Please, provide me with an updated version of the `.po` file.

**Comment by kirmaha** [comment]
Just did it through pull request #2

**Comment by paveloom** [comment]
Thanks! These changes will be live when `v4` is [reviewed](https://extensions.gnome.org/review/35272).
